### ISSUE TITLE
Improve template head to better fit the ultrasond shape

### ISSUE THREAD

**Issue by Benvii** [mdl29/bug-the-biped#1]
We want to have a basic shape for the head (extruded) with the correct shape for the ultrasound this means : 

File to modify is : `freecad_file/tete v2.fcstd`

## On the back side 

See measure here  in this OpenScad file (save it as `*.scad`) : 
```
difference() {
cube(size=[60, 50, 5]);
translate([17, 36, -3]) cylinder(h=10, r=8.5, $fn=100);
translate([43, 36, -3]) cylinder(h=10, r=8.5, $fn=100);
translate([24, 25, 2]) cube(size=[12 ,4 ,10]);
hull() {
translate([26, 43, 2]) cylinder(h=10, r=2, $fn=100);
translate([34, 43, 2]) cylinder(h=10, r=2, $fn=100);
}
}
translate([7, -5, 0]) cube(size=[10, 5, 5]);
translate([43, -5, 0]) cube(size=[10, 5, 5]);
```

Visual here : 
![openscad_back](https://github.com/mdl29/bug-the-biped/assets/1092728/38346920-113c-4b9a-b3b7-1fbab427a7c5)

**Todo :**
- [ ] Add an upper hole
- [ ] Add a down hole
- [ ] Simplify and remove the line of holes

![tete v2-todo-back](https://github.com/mdl29/bug-the-biped/assets/1092728/bea596c2-4580-4f42-811d-0d631471fa27)

## On the front side : 
![tete v2-todo-front](https://github.com/mdl29/bug-the-biped/assets/1092728/719ac8b5-7f67-4d00-a05c-4deec006ecfb)

**Todo :**

- [ ] Remove chanfrin, so that they can easily add stuff on it
